;;; -*- lexical-binding: t; -*-
(defun x-string-at-point ()
  (if (use-region-p)
      (buffer-substring (region-beginning) (region-end))
    (let ((p (point)))
      (buffer-substring
       (save-excursion (goto-char p) (skip-chars-backward "^ \t\n\r{}()[]") (point))
       (save-excursion (goto-char p) (skip-chars-forward "^ \t\n\r{}()[]") (point))))))

(defun x-parse-file-line-column (string)
  (let ((file string)
        (line 0)
        (column 0))
    (cond
     ((string-match "\\`\\(.+\\):\\([0-9]+\\):\\([0-9]+\\)\\'" string)
      (setq file (match-string 1 string)
            line (string-to-number (match-string 2 string))
            column (string-to-number (match-string 3 string))))
     ((string-match "\\`\\(.+\\):\\([0-9]+\\)\\'" string)
      (setq file (match-string 1 string)
            line (string-to-number (match-string 2 string)))))
    (list file line column)))

(defun x-jump-to-file ()
  (interactive)
  (let* ((parsed (x-parse-file-line-column (x-string-at-point)))
         (file (nth 0 parsed))
         (line (nth 1 parsed))
         (column (nth 2 parsed)))
    (unless (file-exists-p file)
      (user-error "(jump-to-file) no such file: %s" file))
    (find-file file)
    (goto-char (point-min))
    (when (> line 0)
      (forward-line (1- line)))
    (when (> column 0)
      (forward-char (1- column)))))

(provide 'x-jump-to-file)